// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: pt/ptgo.proto

package ptfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str1 string `protobuf:"bytes,1,opt,name=str1,proto3" json:"str1,omitempty"`
	Str2 string `protobuf:"bytes,2,opt,name=str2,proto3" json:"str2,omitempty"`
	I3   int64  `protobuf:"varint,3,opt,name=i3,proto3" json:"i3,omitempty"`
	I4   int64  `protobuf:"varint,4,opt,name=i4,proto3" json:"i4,omitempty"`
}

func (x *ProtoMsg) Reset() {
	*x = ProtoMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pt_ptgo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoMsg) ProtoMessage() {}

func (x *ProtoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pt_ptgo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoMsg.ProtoReflect.Descriptor instead.
func (*ProtoMsg) Descriptor() ([]byte, []int) {
	return file_pt_ptgo_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoMsg) GetStr1() string {
	if x != nil {
		return x.Str1
	}
	return ""
}

func (x *ProtoMsg) GetStr2() string {
	if x != nil {
		return x.Str2
	}
	return ""
}

func (x *ProtoMsg) GetI3() int64 {
	if x != nil {
		return x.I3
	}
	return 0
}

func (x *ProtoMsg) GetI4() int64 {
	if x != nil {
		return x.I4
	}
	return 0
}

var File_pt_ptgo_proto protoreflect.FileDescriptor

var file_pt_ptgo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x74, 0x2f, 0x70, 0x74, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x74, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x52, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x72, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x74, 0x72, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x72, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x72, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x34, 0x42, 0x09, 0x5a, 0x07, 0x2f,
	0x70, 0x74, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pt_ptgo_proto_rawDescOnce sync.Once
	file_pt_ptgo_proto_rawDescData = file_pt_ptgo_proto_rawDesc
)

func file_pt_ptgo_proto_rawDescGZIP() []byte {
	file_pt_ptgo_proto_rawDescOnce.Do(func() {
		file_pt_ptgo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pt_ptgo_proto_rawDescData)
	})
	return file_pt_ptgo_proto_rawDescData
}

var file_pt_ptgo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pt_ptgo_proto_goTypes = []interface{}{
	(*ProtoMsg)(nil), // 0: ptfile.ProtoMsg
}
var file_pt_ptgo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pt_ptgo_proto_init() }
func file_pt_ptgo_proto_init() {
	if File_pt_ptgo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pt_ptgo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pt_ptgo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pt_ptgo_proto_goTypes,
		DependencyIndexes: file_pt_ptgo_proto_depIdxs,
		MessageInfos:      file_pt_ptgo_proto_msgTypes,
	}.Build()
	File_pt_ptgo_proto = out.File
	file_pt_ptgo_proto_rawDesc = nil
	file_pt_ptgo_proto_goTypes = nil
	file_pt_ptgo_proto_depIdxs = nil
}
